import { ParsedFlag } from './types';

export function generateTypeScript(flags: ParsedFlag[]): string {
  const timestamp = new Date().toISOString();
  
  const flagsEntries = flags.map(flag => {
    const comment = flag.type === 'multivariate' 
      ? `/** @multivariate variants: ${flag.variants.join(', ')} */`
      : `/** @boolean */`;
    return `  ${comment}\n  ${flag.constName}: '${flag.key}',`;
  }).join('\n');

  const variantTypes = flags
    .filter(f => f.type === 'multivariate')
    .map(f => `  '${f.key}': ${f.variants.map(v => `'${v}'`).join(' | ')};`)
    .join('\n');

  const booleanKeys = flags
    .filter(f => f.type === 'boolean')
    .map(f => `'${f.key}'`)
    .join(' | ') || 'never';

  const multivariateKeys = flags
    .filter(f => f.type === 'multivariate')
    .map(f => `'${f.key}'`)
    .join(' | ') || 'never';

  const metadataEntries = flags.map(flag => {
    return `  '${flag.key}': { type: '${flag.type}', variants: [${flag.variants.map(v => `'${v}'`).join(', ')}] },`;
  }).join('\n');

  return `/**
  * ⚠️  AUTO-GENERATED — DO NOT EDIT MANUALLY
  * Generated by posthog-flag-types
  * Last synced: ${timestamp}
  */

  export const FLAGS = {
  ${flagsEntries}
  } as const;

  export const FLAG_METADATA = {
  ${metadataEntries}
  } as const;

  export type FlagKey = typeof FLAGS[keyof typeof FLAGS];

  export type FlagVariants = {
${variantTypes}
};

export type VariantsOf<K extends keyof FlagVariants> = FlagVariants[K];

export type BooleanFlagKey = ${booleanKeys};
export type MultivariateFlagKey = ${multivariateKeys};

export type FlagOverrides = {
  [K in FlagKey]?: K extends keyof FlagVariants ? FlagVariants[K] : boolean;
};
`;
}
